// @ts-ignore
import Head from "next/head";
import { Inter } from "@next/font/google";
import { getPosts } from "../utilities/posts";
import { getSettings } from "../utilities/settings";
import { Post } from "../utilities/types";
import Navigation from "../components/Navigation";
import BlogList from "@/components/blogList";

type Props = {
  posts: any;
  settings: any;
};

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts, settings }: Props) {
  return (
    <>
      <Head>
        <title>Digics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-5">
        <Navigation settings={settings} logo={settings.logo} />
        <div>
          <h1 className=" font-semibold text-8xl max-w-4xl m-5 ">We create, build and host the new era of digital</h1>
        </div>
        <BlogList posts={posts} />
        <ul>
          {posts.map((post: Post) => (
            <li key={post.id}>{post.title}</li>
          ))}
        </ul>
      </main>
    </>
  );
}

export async function getStaticProps(context: any) {
  const posts = await getPosts();
  const settings = await getSettings();

  if (!posts) {
    return {
      notFound: true,
    };
  }

  if (!settings) {
    return {
      notFound: true,
    };
  }

  return {
    props: { posts, settings },
  };
}
