// @ts-ignore
import Head from "next/head";
import { Inter } from "@next/font/google";
import { getPosts } from "../utilities/posts";
import { getSettings } from "../utilities/settings";
import Navigation from "../components/Navigation";
import BlogList from "../components/BlogList";
import FeaturesList from "../components/FeaturesList";
import HeaderBlock from "@/components/HeaderBlock";
import LogoCloud from "@/components/LogoCloud";
import SaleBanner from "@/components/SaleBanner";
import InformationFeature from "@/components/InformationFeature";
import NewsletterSignup from "@/components/NewsletterSignup";
import PricingBlock from "@/components/PricingBlock";

type Props = {
  posts: any;
  settings: any;
};

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts, settings }: Props) {
  return (
    <>
      <Head>
        <title>Digics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <SaleBanner /> */}
        <Navigation data={settings} />
        <HeaderBlock data={settings} />
        <LogoCloud />
        <InformationFeature />
        <BlogList data={posts} />
        <PricingBlock />
        <NewsletterSignup />
      </main>
    </>
  );
}

export async function getStaticProps(context: any) {
  const posts = await getPosts();
  const settings = await getSettings();

  if (!posts) {
    return {
      notFound: true,
    };
  }

  if (!settings) {
    return {
      notFound: true,
    };
  }

  return {
    props: { posts, settings },
  };
}
